# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-last_modified_time']},
        ),
    ]
