# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20160907_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='昵称')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('user_email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
    ]
