# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('y', '已登录'), ('n', '未登录')], default='n', max_length=1, verbose_name='登录状态'),
        ),
    ]
