# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20160910_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='account',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='account',
            name='homepage',
            field=models.URLField(blank=True, null=True, verbose_name='主页'),
        ),
        migrations.AddField(
            model_name='account',
            name='weibo',
            field=models.URLField(blank=True, null=True, verbose_name='微博'),
        ),
    ]
